[package]
name = "Saloon-Tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.2"
bevy_common_assets = { version = "0.14.0", features = ["ron"] }
bevy_ecs_tilemap = "0.17.0"
ron = "0.11.0"
serde = { version = "1.0.228", features = ["derive"]}

